version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "8845:8845"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Tingeso
    ports:
      - 5432:5432
  app1:
    container_name: evaluacion1_1
    image: jeanlucasofm/evaluacion1
    ports:
      - "8844:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/Tingeso?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db